### ISSUE TITLE
Caching JWK

### ISSUE THREAD

**Issue by jacekschae** [ovotech/ring-jwt#15]
Hi there,

I have a question regarding a function. We are doing memoize so that we don't have to recheck on every request agains an endpoint `https://domain.com/.well-known/jwks.json`

```clojure
(def rsa-key-provider
  (memoize
    (fn [url]
      (let [jwk-provider (new-jwk-provider url)]
        (reify RSAKeyProvider
          (getPublicKeyById [_ key-id]
            (-> (.get jwk-provider key-id)
                (.getPublicKey)))
          (getPrivateKey [_] nil)
          (getPrivateKeyId [_] nil))))))
```

https://github.com/ovotech/ring-jwt/blob/ec84cc6371ea4e311629a71c05323875c9fcbd65/src/ring/middleware/jwk.clj#L13

From my understanding this cache would be invalidated only when you restart your service. Is there any other option to invalidate that? Would it be worth to think about that? Maybe it doesn't make sense, since it seems like the `.well-known` would almost [never change](https://community.auth0.com/t/auth0-failures-getting-well-known-jwks-json/13863)?

Would be great to hear your opinion about this one.

Thanks, Jacek

**Comment by kelveden** [comment]
@jacekschae Thanks for the question and sorry for the delay. You're correct that the implication is that a service would need to restart to pick up a new jwks configuration. It's a fair point. Some sort of TTL on the cache would probably make most sense; I'll have a think about that.

**Comment by kelveden** [comment]
Ah wait, I misread the code. The memoizing is around the creation of the provider, **not** the calls to pull back keys. So new keys would be picked up immediately.

**Comment by jacekschae** [comment]
@kelveden thanks for your reply. I'm not sure if I'm getting this 🤔

Just reading the code, when we call the `ring.middleware.token/decode :RS256` we memoize the provider ... . Does this mean that on every request we are checking the `.well-known` and if it's still valid? If not when would that be triggered?

**Comment by kelveden** [comment]
@jacekschae there are two levels of caching going on in fact:

1. the memoization around pulling back the provider itself (i.e. https://github.com/ovotech/ring-jwt/blob/master/src/ring/middleware/jwk.clj#L13) .
2. the use of [GuavaCachedJwkProvider](https://github.com/auth0/jwks-rsa-java/blob/master/src/main/java/com/auth0/jwk/GuavaCachedJwkProvider.java#L27) here: https://github.com/ovotech/ring-jwt/blob/master/src/ring/middleware/jwk.clj#L10. So each call to get the `.well-known` will pull from the cache that `GuavaCachedJwkProvider` provides - i.e. "up to" 10 minutes.

**Comment by kelveden** [comment]
(I've updated the README today to hopefully better explain this.)

**Comment by jacekschae** [comment]
@kelveden - I see, thanks for pointing at Guava. 

BTW. I don't know if you are aware but I'm using this library in a video course - [LearnReitit.com](https://www.learnreitit.com). If you would be interesting in getting access - let me know.

**Comment by kelveden** [comment]
@jacekschae glad to hear that the library is proving useful! It's always interesting to see how other folks are using libs that one has helped to create so certainly it'd be interesting to view if it's no bother.
