### ISSUE TITLE
Reflective calls in token.clj

### ISSUE THREAD

**Issue by dpiliouras** [ovotech/ring-jwt#16]
Hi there,

First of all many thanks for putting this together 👍 . Secondly, there are a bunch of reflective calls in `token.clj`, but I would suggest running the project  against `lein check`, as there may be more.  Thirdly, do you happen to know what `:alg`/`:enc` I would need to use with `buddy-sign` in order to generate a token that is then decode-able by this `ovotech/ring-jwt`? I tried various combinations, but I always get `The token was expected to have 3 parts, but got 5` :(. Sample code follows:

```clj
(-> payload
      (buddy.sign.jwt/encrypt
        (sha/sha256 secret nil) ;; need 32 bytes
        {:alg :dir ;;  also tried :a128kw, :a192kw, :a256kw
         :enc :a128cbc-hs256} ;; also tried :a256gcm
       ))
``` 

Many thanks in advance...

**Comment by dpiliouras** [comment]
Ah - nevermind...this project doesn't deal with JWE - only JWS, right?

**Comment by kelveden** [comment]
@dpiliouras thanks for getting in touch; sorry for the delay in replying.

You are correct that there's no explicit support for JWE in the library currently. That's not to say that there couldn't be of course! but it's not something on our radar at the moment.
