### ISSUE TITLE
[FEATURE] Option to disable validation when running offline (eg for local dev on a plane)

### ISSUE THREAD

**Issue by avocade** [ovotech/ring-jwt#18]
Would be nice to fully disable the validation (including downloading of the JWKS, and checking expiry) when developing locally or testing, eg using a hardcoded JWT. This would still do the unpacking of the token payload into `:claims` etc.

A `:skip-validation true` setting could be added dynamically when in dev mode.

I'll do a PR for this eventually when the pain becomes greater, just wanted to record my thoughts :)

**Comment by kelveden** [comment]
I'm not a fan of this idea for a few reasons:

* it's trying to solve a problem that really should be the domain of configuration management or an IOC container.
* it opens the possibility of validation being erroneously switched off - there would be no errors or warnings in the service using the library to indicate that validation was being skipped.

Personally the way I handle this running locally business is just re-configure something like this:

```clj
(jwt/wrap-jwt handler {:no-issuer {:alg    :HS256
                                   :secret "mysimplesecret"}})
```

I also tend to use an IOC - in my case [Duct](https://github.com/ovotech/duct.middleware.ring-jwt) - which makes the switching out configurations even easier.

**Comment by kelveden** [comment]
I should also add to the above comment - creating requests that are acceptable to the middleware is then just a matter of encoding a token with appropriate claims; e.g. https://github.com/ovotech/ring-jwt/blob/master/test/ring/middleware/token_hs256_test.clj#L12-L19.
